/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.mjg01.tombolaorganizer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void justAnswerWithTrue() {
        assertTrue(true);
    }
}
