/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.mjg01.tombolaorganizer;

import javafx.application.Application;
import javafx.scene.control.Label;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage stage) {
        Label label = new Label("Hello, JavaFX!");
        StackPane root = new StackPane(label);

        Scene scene = new Scene(root, 400, 250);

        stage.setTitle("Tombola Organizer");
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
